"use client";

export default function InterviewsPage() {
  return (
    <>
      <h1 className="page-title">Interview Hub</h1>
      <p className="page-subtitle">Auto-generated questions and interview schedules.</p>

      <div className="content-grid">
        <div className="panel light-orange">
          <h2>Upcoming Interviews</h2>
          <div className="ranking-list" style={{ marginTop: '20px' }}>
             <p style={{ color: '#555', fontSize: '14px' }}>No upcoming interviews scheduled. Move candidates to the interview stage to see them here.</p>
          </div>
        </div>

        <div className="panel green">
          <h2>Generated Question Banks</h2>
          <p style={{ fontSize: '14px', color: '#555', marginBottom: '20px' }}>
            Tailored questions generated by the LLM based on candidate weaknesses and job requirements.
          </p>
          
          <div className="ranking-list">
             <p style={{ color: '#555', fontSize: '14px' }}>No question banks generated yet. Go to a Job's candidate rankings to generate custom questions.</p>
          </div>
        </div>
      </div>
    </>
  );
}
